--- #YAML:1.0
name:               CIF-Client
version:            0.00_01
abstract:           Perl extension that extends REST::Client for use with the CI-Framework REST interface 
author:
    - Wes Young <wes@>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Getopt::Std:   ~
    JSON:          ~
    REST::Client:  ~
    Text::Table:   ~
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
