---
abstract: 'Perl extension that extends REST::Client for use with the CI-Framework REST interface '
author:
  - 'REN-ISAC and The Trustees of Indiana University '
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CIF-Client
no_index:
  directory:
    - inc
    - t
requires:
  Class::Accessor: 0.31
  Compress::Zlib: 2.008
  Config::Simple: 4.58
  Digest::MD5: 2.36
  Digest::SHA1: 2.11
  HTML::Table: 2.08
  HTTP::Server::Simple: 0
  JSON: 2.07
  LWP::Protocol::https: 0
  Module::Install: 1.00
  Module::Pluggable: 3.6
  REST::Client: 243
  Regexp::Common::net: 2.108
  Regexp::Common::net::CIDR: 0.02
  Snort::Rule: 1.07
  Text::Table: 1.114
  perl: 5.8.8
resources:
  license: http://dev.perl.org/licenses/
version: 0.05
